### ISSUE TITLE
Criar os protótipos de interface no figma

### ISSUE THREAD

**Issue by karinepcdc** [filipegmedeiros/gatinhos_ufrn#6]
Páginas a serem prototipadas:
- [x] Login (para o administrador apenas)
- [x] Listagem de gatos para adoção
- [x] Cadastro de gatos para adoção
- [x] Cadastro de interesse em adoção de gato
- [x] Listagem de pedidos de adoção de gatos (visível para administrador apenas)

**Comment by santanasara** [comment]
Link com as telas: https://www.figma.com/file/0PyWPleqpypUsmxwiaOh1o/Gatinhos-UFRN-Flutter?node-id=4%3A5821
